version: '1.0'
name: pipeline-autopublish
displayName: pipeline-autopublish
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-163c59b9
    displayName: autopublish
    strategy: naturally
    trigger: auto
    executor:
      - chenxin199305
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
